DROP TABLE IF EXISTS Goal;
DROP TABLE IF EXISTS Achievement;

CREATE TABLE Goal (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    goalName TEXT NOT NULL,
    frequency TEXT NOT NULL,
    completed BOOLEAN, 
    numCompleted INTEGER,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Achievement (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    completed TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    goal_id INTEGER,
    FOREIGN KEY (goal_id) REFERENCES Goal (id) 
);
