DROP TABLE IF EXISTS Goal;
DROP TABLE IF EXISTS Achievement;

CREATE TABLE Goal (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    goalName TEXT NOT NULL,
    frequency TEXT NOT NULL,
    completed BOOLEAN, 
    numCompleted INTEGER
);

CREATE TABLE Achievement (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    goalID INTEGER,
    FOREIGN KEY (goalID) REFERENCES Goal(id) 
)
