DROP TABLE IF EXISTS Goal;
DROP TABLE IF EXISTS Achievement;
DROP TABLE IF EXISTS User;

CREATE TABLE Goal (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    goalName TEXT NOT NULL,
    frequency TEXT NOT NULL,
    completed BOOLEAN DEFAULT "0", 
    numCompleted INTEGER DEFAULT "0",
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES User (id)
);

CREATE TABLE Achievement (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    completed TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    goal_id INTEGER,
    FOREIGN KEY (goal_id) REFERENCES Goal (id),
    FOREIGN KEY (user_id) REFERENCES User (id)
);

CREATE TABLE User (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

